spring.datasource.url=jdbc:mysql://localhost:3306/ae4_seguridad?useSSL=false&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=TU_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
server.port=8080
